### ISSUE TITLE
Open to a helm chart refactor?

### ISSUE THREAD

**Issue by acelinkio** [project-zot/helm-charts#51]
This chart has an unconventional way of configuring values.  Here are a couple examples:

**Pesistence**
persistence is a boolean instead of a map.  Many other charts use the following setup:
```yaml
persistence:
  enabled: false
  size: 8Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  existingClaim: ""
```

compared to the current setup of
```yaml
persistence: false
pvc:
  create: false
  name: null
  accessMode: "ReadWriteOnce" # (this should be a list anyways)
  storage: 8Gi
  storageClassName: null
  ```

**httpGet**
This setting is used by container probes and some post deployment tests.  Probes go directly from the kubelet to the pod directly and avoid the ingress controller.  https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

As far as I can tell, this chart expects the TLS termination to happen on the ingress.  The only reason why this setting is needed is configuring your tests https://github.com/project-zot/helm-charts/blob/main/charts/zot/templates/tests/

**Tests**
Most helm charts don't bother with tests.  One reason for this is it relies upon helm hooks to provide some orchestration.  Would consider entirely.
